# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/si07886/OneDrive - Habib University/khtm ho ye project/khtm ho ye project/khtm ho ye project.srcs/sources_1/new/pong_game.xdc

# IP: new/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
